Potential enhancement to add any freetext as display name
johnstonskj/rust-email_address pull request #15
Opened 2023-02-28 08:11 UTC by ghandic

closes #14

2023-03-05 01:48 UTC, johnstonskj requested changes

2023-03-05 01:48 UTC, johnstonskj commented on src/lib.rs
> +            let email = &left_right.1[0..left_right.1.len() - 1];
I assume the -1 is to drop the final `'>'` but this doesn't work if padded. I would make sure we call trim() on both parts before returning

2023-10-18 03:24 UTC, 1oglop1 commented on src/lib.rs
> +            let email = &left_right.1[0..left_right.1.len() - 1];
@ghandic Any progress on this?

2024-07-04 02:42 UTC, johnstonskj commented on src/lib.rs
> +            let email = &left_right.1[0..left_right.1.len() - 1];
I thought it was bounced back to you to update the PR

2024-07-04 02:49 UTC, johnstonskj approved these changes

2024-07-19 14:56 UTC, johnstonskj commented
Will put up a separate commit to merge this

2024-07-19 14:56 UTC, closed without merging